name: Cross-Compile and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: windows-latest
            runtime: win-x64
          - os: macos-latest
            runtime: osx-x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore macOS workload
      if: matrix.os == 'macos-latest'
      run: dotnet workload restore

    - name: Restore dependencies
      run: dotnet restore YTSubConverter.sln

    - name: Build
      run: dotnet build YTSubConverter.sln --configuration Release

    - name: Publish
      run: dotnet publish YTSubConverter.UI.Linux/YTSubConverter.UI.Linux.csproj --configuration Release --runtime ${{ matrix.runtime }} --self-contained false --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: YTSubConverter-${{ matrix.runtime }}
        path: ./publish